/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DefineRouteImport } from './routes/define'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnforceChecksRouteImport } from './routes/enforce.checks'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DefineRoute = DefineRouteImport.update({
  id: '/define',
  path: '/define',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnforceChecksRoute = EnforceChecksRouteImport.update({
  id: '/enforce/checks',
  path: '/enforce/checks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/enforce/checks': typeof EnforceChecksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/enforce/checks': typeof EnforceChecksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/enforce/checks': typeof EnforceChecksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/define' | '/pricing' | '/settings' | '/enforce/checks'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/define' | '/pricing' | '/settings' | '/enforce/checks'
  id:
    | '__root__'
    | '/'
    | '/define'
    | '/pricing'
    | '/settings'
    | '/enforce/checks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefineRoute: typeof DefineRoute
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  EnforceChecksRoute: typeof EnforceChecksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/define': {
      id: '/define'
      path: '/define'
      fullPath: '/define'
      preLoaderRoute: typeof DefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enforce/checks': {
      id: '/enforce/checks'
      path: '/enforce/checks'
      fullPath: '/enforce/checks'
      preLoaderRoute: typeof EnforceChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefineRoute: DefineRoute,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  EnforceChecksRoute: EnforceChecksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
