/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServeRouteImport } from './routes/serve'
import { Route as ExperimentRouteImport } from './routes/experiment'
import { Route as DefineRouteImport } from './routes/define'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServeRoute = ServeRouteImport.update({
  id: '/serve',
  path: '/serve',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperimentRoute = ExperimentRouteImport.update({
  id: '/experiment',
  path: '/experiment',
  getParentRoute: () => rootRouteImport,
} as any)
const DefineRoute = DefineRouteImport.update({
  id: '/define',
  path: '/define',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/experiment': typeof ExperimentRoute
  '/serve': typeof ServeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/experiment': typeof ExperimentRoute
  '/serve': typeof ServeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/define': typeof DefineRoute
  '/experiment': typeof ExperimentRoute
  '/serve': typeof ServeRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/define' | '/experiment' | '/serve' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/define' | '/experiment' | '/serve' | '/settings'
  id: '__root__' | '/' | '/define' | '/experiment' | '/serve' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefineRoute: typeof DefineRoute
  ExperimentRoute: typeof ExperimentRoute
  ServeRoute: typeof ServeRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serve': {
      id: '/serve'
      path: '/serve'
      fullPath: '/serve'
      preLoaderRoute: typeof ServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiment': {
      id: '/experiment'
      path: '/experiment'
      fullPath: '/experiment'
      preLoaderRoute: typeof ExperimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/define': {
      id: '/define'
      path: '/define'
      fullPath: '/define'
      preLoaderRoute: typeof DefineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefineRoute: DefineRoute,
  ExperimentRoute: ExperimentRoute,
  ServeRoute: ServeRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
